// <auto-generated />
using System;
using GBCSporting2021__TEAM_MYK_.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GBCSporting2021__TEAM_MYK_.Migrations
{
    [DbContext(typeof(SportingContext))]
    [Migration("20210226001246_Updated_MG")]
    partial class Updated_MG
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Brunei"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Tajikistan"
                        });
                });

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "1396 Harvest Moon Dr",
                            City = "Balykchy",
                            CountryId = 1,
                            Email = "yp.yoo@georgebrown.ca",
                            Firstname = "YP",
                            Lastname = "Yoo",
                            Phone = "4167240128",
                            Postalcode = "L3R 0L7",
                            State = "Bishkek"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "1863 Lynden Road",
                            City = "Tutong",
                            CountryId = 2,
                            Email = "mark.tres@georgebrown.ca",
                            Firstname = "Mark",
                            Lastname = "Tres",
                            Phone = "4161720326",
                            Postalcode = "L0B 1B0",
                            State = "Belait"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "4354 Wallace Street",
                            City = "Panjakent",
                            CountryId = 3,
                            Email = "kent.pedro@georgebrown.ca",
                            Firstname = "Kent",
                            Lastname = "Pedro",
                            Phone = "4161932185",
                            Postalcode = "V9R 3A8",
                            State = "Norak"
                        });
                });

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOpened")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            CustomerId = 1,
                            DateClosed = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(968),
                            DateOpened = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(623),
                            Description = "Hello :)",
                            ProductId = 1,
                            TechnicianId = 1,
                            Title = "Could not fix"
                        },
                        new
                        {
                            IncidentId = 2,
                            CustomerId = 2,
                            DateClosed = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(1320),
                            DateOpened = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(1307),
                            Description = "Hi :(",
                            ProductId = 2,
                            TechnicianId = 2,
                            Title = "Could not open"
                        },
                        new
                        {
                            IncidentId = 3,
                            CustomerId = 3,
                            DateClosed = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(1331),
                            DateOpened = new DateTime(2021, 2, 25, 19, 12, 45, 512, DateTimeKind.Local).AddTicks(1328),
                            Description = "Yes",
                            ProductId = 3,
                            TechnicianId = 3,
                            Title = "Could not turn on"
                        });
                });

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "QWE123",
                            Name = "TV",
                            Price = "$999.99",
                            ReleaseDate = new DateTime(2021, 2, 25, 19, 12, 45, 507, DateTimeKind.Local).AddTicks(5152)
                        },
                        new
                        {
                            ProductId = 2,
                            Code = "ASD456",
                            Name = "Sofa",
                            Price = "$555.55",
                            ReleaseDate = new DateTime(2021, 2, 25, 19, 12, 45, 510, DateTimeKind.Local).AddTicks(9441)
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "ZXC789",
                            Name = "Laptop",
                            Price = "$2.00",
                            ReleaseDate = new DateTime(2021, 2, 25, 19, 12, 45, 510, DateTimeKind.Local).AddTicks(9467)
                        });
                });

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Email = "tech1@georgebrown.ca",
                            Name = "Technician1",
                            Phone = "4168540113"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Email = "tech2@gerogebrown.ca",
                            Name = "Technician2",
                            Phone = "4167542904"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Email = "tech3@georgebrown.ca",
                            Name = "Technician3",
                            Phone = "4167125209"
                        });
                });

            modelBuilder.Entity("GBCSporting2021__TEAM_MYK_.Models.Incident", b =>
                {
                    b.HasOne("GBCSporting2021__TEAM_MYK_.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSporting2021__TEAM_MYK_.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSporting2021__TEAM_MYK_.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Technician");
                });
#pragma warning restore 612, 618
        }
    }
}
